<a href="https://colab.research.google.com/github/rosimotasp/postech/blob/main/Fase_04_Machine_learning_medicospynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

url = 'https://raw.githubusercontent.com/rosimotasp/postech/main/Obesity%20(1).csv'
df = pd.read_csv(url)
print(df.columns)

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history', 'FAVC', 'FCVC',
       'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS',
       'Obesity'],
      dtype='object')

In [5]:
X = df.drop(columns=['Obesity'])
y = df['Obesity']

In [6]:
y = df['Obesity']
X = pd.get_dummies(df.drop(columns=['Obesity']))

In [7]:
# Passo 1: Importar bibliotecas
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Passo 2: Carregar o dataset do GitHub
url = 'https://raw.githubusercontent.com/rosimotasp/postech/main/Obesity%20(1).csv'
df = pd.read_csv(url)

# Passo 3: Separar variável alvo antes dos dummies
y = df['Obesity']
X = pd.get_dummies(df.drop(columns=['Obesity']))

# Passo 4: Treinar modelo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Passo 5: Avaliação
y_pred = model.predict(X_test)
print(f"Acurácia do modelo: {accuracy_score(y_test, y_pred) * 100:.2f}%")

# Passo 6: Salvar modelo
with open('random_forest_obesity_model.pkl', 'wb') as f:
    pickle.dump(model, f)

# Passo 7: Simular previsão
dados = {
    'Gender': ['Male'],
    'Age': [25],
    'Height': [1.75],
    'Weight': [85],
    'family_history': ['yes'],
    'FAVC': ['yes'],
    'FCVC': [2],
    'NCP': [3],
    'CAEC': ['Sometimes'],
    'SMOKE': ['no'],
    'CH2O': [2],
    'SCC': ['no'],
    'FAF': [3],
    'TUE': [1],
    'CALC': ['Sometimes'],
    'MTRANS': ['Public_Transportation']
}
df_sim = pd.get_dummies(pd.DataFrame(dados))
for col in X.columns:
    if col not in df_sim.columns:
        df_sim[col] = 0
df_sim = df_sim[X.columns]
pred = model.predict(df_sim)
print(f"Nível de obesidade previsto: {pred[0]}")

Acurácia do modelo: 93.14%
Nível de obesidade previsto: Overweight_Level_II

In [12]:
import pandas as pd

# Carregar o dataset do GitHub
url = 'https://raw.githubusercontent.com/rosimotasp/postech/main/Obesity%20(1).csv'
df = pd.read_csv(url)

# Renomear e padronizar os nomes das colunas
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

# Converter tipos de dados
df['age'] = df['age'].astype(int)
df['height'] = df['height'].astype(float)
df['weight'] = df['weight'].astype(float)

# Preencher valores ausentes com padrões razoáveis
df.fillna({
    'family_history': 'no',
    'favc': 'no',
    'fcvc': 2,
    'ncp': 3,
    'caec': 'Sometimes',
    'smoke': 'no',
    'ch2o': 2,
    'scc': 'no',
    'faf': 3,
    'tue': 1,
    'calc': 'Sometimes',
    'mtrans': 'Public_Transportation'
}, inplace=True)

# Padronizar categorias
df['Genero'] = df['gender'].str.capitalize()
df['family_history'] = df['family_history'].str.lower()
df['favc'] = df['favc'].str.lower()
df['caec'] = df['caec'].str.capitalize()
df['smoke'] = df['smoke'].str.lower()
df['scc'] = df['scc'].str.lower()
df['calc'] = df['calc'].str.capitalize()
df['mtrans'] = df['mtrans'].str.replace(' ', '_').str.capitalize()

# Visualizar os dados tratados
df.head()

,gender,age,height,weight,family_history,favc,fcvc,ncp,caec,smoke,ch2o,scc,faf,tue,calc,mtrans,obesity,Genero
0,Female,21,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,No,Public_transportation,Normal_Weight,Female
1,Female,21,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_transportation,Normal_Weight,Female
2,Male,23,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_transportation,Normal_Weight,Male
3,Male,27,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Male
4,Male,22,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_transportation,Overweight_Level_II,Male

In [13]:
import pandas as pd

# Carregar o dataset do GitHub
url = 'https://raw.githubusercontent.com/rosimotasp/postech/main/Obesity%20(1).csv'
df = pd.read_csv(url)

# Padronizar e traduzir os nomes das colunas
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
df.rename(columns={
    'gender': 'genero',
    'age': 'idade',
    'height': 'altura',
    'weight': 'peso',
    'family_history': 'historico_familiar',
    'favc': 'consumo_calorico',
    'fcvc': 'consumo_vegetais',
    'ncp': 'refeicoes_dia',
    'caec': 'lanches',
    'smoke': 'fuma',
    'ch2o': 'consumo_agua',
    'scc': 'controle_calorias',
    'faf': 'atividade_fisica',
    'tue': 'uso_tecnologia',
    'calc': 'consumo_alcool',
    'mtrans': 'meio_transporte',
    'obesity': 'obesidade'
}, inplace=True)

# Visualizar os dados com cabeçalhos em português
df.head()

,genero,idade,altura,peso,historico_familiar,consumo_calorico,consumo_vegetais,refeicoes_dia,lanches,fuma,consumo_agua,controle_calorias,atividade_fisica,uso_tecnologia,consumo_alcool,meio_transporte,obesidade
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [15]:
# Traduzir valores das colunas categóricas
df['genero'] = df['genero'].replace({'Male': 'Masculino', 'Female': 'Feminino'})
df['historico_familiar'] = df['historico_familiar'].replace({'yes': 'sim', 'no': 'não'})
df['consumo_calorico'] = df['consumo_calorico'].replace({'yes': 'sim', 'no': 'não'})
df['lanches'] = df['lanches'].replace({'no': 'não', 'Sometimes': 'às vezes', 'Frequently': 'frequentemente', 'Always': 'sempre'})
df['fuma'] = df['fuma'].replace({'yes': 'sim', 'no': 'não'})
df['controle_calorias'] = df['controle_calorias'].replace({'yes': 'sim', 'no': 'não'})
df['consumo_alcool'] = df['consumo_alcool'].replace({'no': 'não', 'Sometimes': 'às vezes', 'Frequently': 'frequentemente', 'Always': 'sempre'})
df['meio_transporte'] = df['meio_transporte'].replace({
    'Automobile': 'Automóvel',
    'Bike': 'Bicicleta',
    'Motorbike': 'Motocicleta',
    'Public_Transportation': 'Transporte Público',
    'Walking': 'Caminhada'
})
df['obesidade'] = df['obesidade'].replace({
    'Normal_Weight': 'peso_normal',
    'Overweight_Level_I': 'sobrepeso_nivel_1',
    'Overweight_Level_II': 'sobrepeso_nivel_2',
    'Obesity_Type_I': 'obesidade_tipo_1',
    'Obesity_Type_II': 'obesidade_tipo_2',
    'Obesity_Type_III': 'obesidade_tipo_3',
    'Insufficient_Weight': 'peso_insuficiente'
})# Visualizar os dados com cabeçalhos em português
df.head()

,genero,idade,altura,peso,historico_familiar,consumo_calorico,consumo_vegetais,refeicoes_dia,lanches,fuma,consumo_agua,controle_calorias,atividade_fisica,uso_tecnologia,consumo_alcool,meio_transporte,obesidade
0,Feminino,21.0,1.62,64.0,sim,não,2.0,3.0,às vezes,não,2.0,não,0.0,1.0,não,Transporte Público,peso_normal
1,Feminino,21.0,1.52,56.0,sim,não,3.0,3.0,às vezes,sim,3.0,sim,3.0,0.0,às vezes,Transporte Público,peso_normal
2,Masculino,23.0,1.80,77.0,sim,não,2.0,3.0,às vezes,não,2.0,não,2.0,1.0,frequentemente,Transporte Público,peso_normal
3,Masculino,27.0,1.80,87.0,não,não,3.0,3.0,às vezes,não,2.0,não,2.0,0.0,frequentemente,Caminhada,sobrepeso_nivel_1
4,Masculino,22.0,1.78,89.8,não,não,2.0,1.0,às vezes,não,2.0,não,0.0,0.0,às vezes,Transporte Público,sobrepeso_nivel_2